version: "3.8"
services:
  test-db:
    image: postgres:13.3
    container_name: test_postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  test-runner:
    container_name: test-runner-phone
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://test-db:5432/test_db
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: test_pass

networks:
  my_bridge:
    driver: bridge

# команда для запуска в терминале контейнеры останутся:
# docker-compose -f docker-compose-test.yml up --build