version: '3.8'
services:
  postgres:
    image: postgres:13.3
    container_name: phone_hashing
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phone_hashing




