#version: "3.8"
services:
  test-db:
    image: postgres:13.3
    container_name: test_postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: >
      postgres
      -c shared_buffers=8GB
      -c work_mem=1GB
      -c maintenance_work_mem=2GB
      -c checkpoint_timeout=30min
      -c wal_buffers=1GB
      -c max_wal_size=8GB
#      -c synchronous_commit=off
#      -c fsync=off
#      -c full_page_writes=off


  test-runner:
    container_name: test-runner-phone
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://test-db:5432/test_db
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: test_pass
#    ports:
#      - "8083:8083"
#    networks:
#      - my_bridge

networks:
  my_bridge:
    driver: bridge

#server:
#  port: 8083
#  address: 0.0.0.0



# команда для запуска в терминале: docker-compose -f docker-compose-test.yml up --abort-on-container-exit