spring:
  datasource:
    url: jdbc:postgresql://test-db:5432/test_db
    username: test_user
    password: test_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration/common,classpath:/db/migration/test
    placeholders:
      hash_algorithm: SHA1
      salt: salt_value
#    baseline-on-migrate: true
  application:
    name: phone-hashing-service-test

logging:
  level:
    org.springframework: ERROR

hashing:
  algorithm: SHA1
  salt: salt_value
  allowed-number-of-collisions: 3








