spring:
  application:
    name: phone-hashing-service
  datasource:
    url: jdbc:postgresql://localhost:5433/phone_hashing
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:/db/migration/common,classpath:/db/migration/dev
    placeholders:
      # SHA1, SHA2, SHA3
      hash_algorithm: SHA1 #
      salt: salt_value

hashing:
  algorithm: SHA1  # SHA1, SHA2, SHA3
  salt: salt_value
  allowed-number-of-collisions: 3

