spring:
  application:
    name: phone-hashing-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:/db/migration/common,classpath:/db/migration/prod
    placeholders:
      hash_algorithm: ${APP_HASH_ALGORITHM}
      salt: ${APP_SALT}

management:
  endpoint:
    startup:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org.springframework: DEBUG

hashing:
  algorithm: ${APP_HASH_ALGORITHM} # SHA1, SHA2, SHA3
  salt: ${APP_SALT} #salt_value
  allowed-number-of-collisions: ${ALLOWED_NUMBER_OF_COLLISIONS} #10



#  metrics:
#    tags:
#      application: phone-hashing-service-prod
